=== Daniel-Fernandez-UBU/riskRealUBU/java/riskrealApp/src/main/resources/quiz_schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1717604831.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"id",
		"maxvalue",
		"title",
		"image",
		"language",
		"description",
		"type",
		"questions"
	],
	"properties": {
		"id": {
			"$id": "#root/id", 
			"title": "Id", 
			"type": "integer",
			"examples": [
				1
			],
			"default": 0
		},"maxvalue": {
			"$id": "#root/maxvalue", 
			"title": "Maxvalue", 
			"type": "integer",
			"examples": [
				10
			],
			"default": 0
		},
		"title": {
			"$id": "#root/title", 
			"title": "Title", 
			"type": "string",
			"default": "",
			"examples": [
				"Habilidades Blandas"
			],
			"pattern": "^.*$"
		},
		"image": {
			"$id": "#root/image", 
			"title": "Image", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/image/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"principalHD.jpg"
				],
				"pattern": "^.*$"
			}
		},
		"language": {
			"$id": "#root/language", 
			"title": "Language", 
			"type": "string",
			"default": "",
			"examples": [
				"es"
			],
			"pattern": "^.*$"
		},
		"description": {
			"$id": "#root/description", 
			"title": "Description", 
			"type": "string",
			"default": "",
			"examples": [
				"Descripción del cuestionario"
			],
			"pattern": "^.*$"
		},
		"type": {
			"$id": "#root/type", 
			"title": "Type", 
			"type": "integer",
			"examples": [
				1
			],
			"default": 0
		},
		"questions": {
			"$id": "#root/questions", 
			"title": "Questions", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/questions/items", 
				"title": "Items", 
				"type": "object",
				"required": [
					"id",
					"description",
					"image",
					"answers",
					"skill"
				],
				"properties": {
					"id": {
						"$id": "#root/questions/items/id", 
						"title": "Id", 
						"type": "integer",
						"examples": [
							1
						],
						"default": 0
					},
					"description": {
						"$id": "#root/questions/items/description", 
						"title": "Description", 
						"type": "string",
						"default": "",
						"examples": [
							"Me familiarizo fácilmente con gente nueva"
						],
						"pattern": "^.*$"
					},
					"image": {
						"$id": "#root/questions/items/image", 
						"title": "Image", 
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/questions/items/image/items", 
							"title": "Items", 
							"type": "string",
							"default": "",
							"examples": [
								"paris.jpg"
							],
							"pattern": "^.*$"
						}
					},
					"answers": {
						"$id": "#root/questions/items/answers", 
						"title": "Answers", 
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/questions/items/answers/items", 
							"title": "Items", 
							"type": "object",
							"required": [
								"text",
								"value",
								"id"
							],
							"properties": {
								"text": {
									"$id": "#root/questions/items/answers/items/text", 
									"title": "Text", 
									"type": "string",
									"default": "",
									"examples": [
										"1 - Totalmente en desacuerdo"
									],
									"pattern": "^.*$"
								},
								"image": {
									"$id": "#root/questions/items/answers/items/image", 
									"title": "Image", 
									"type": "string",
									"default": "",
									"examples": [
										"principalHD.jpg"
									],
									"pattern": "^.*$"
								},
								"value": {
									"$id": "#root/questions/items/answers/items/value", 
									"title": "Value", 
									"type": "integer",
									"examples": [
										1
									],
									"default": 0
								},
								"id": {
									"$id": "#root/questions/items/answers/items/id", 
									"title": "Id", 
									"type": "integer",
									"examples": [
										1
									],
									"default": 0
								}
							}
						}

					},
					"skill": {
						"$id": "#root/questions/items/skill", 
						"title": "Skill", 
						"type": "integer",
						"examples": [
							1
						],
						"default": 0
					}
				}
			}

		}
	}
}

=== Daniel-Fernandez-UBU/riskRealUBU/riskreal/appFiles/jsonFiles/lang/test_quiz_es.json
{	
    "id": 1,
	"maxvalue": 5,
    "title": "Habilidades Blandas",
	"image": [
		"quizMain.png"
		],
    "language": "es",
	"description": "Bienvenido al cuestionario de autoevaluación de habilidades blandas RiskRealApp. Se le van a presentar 5 preguntas de opción múltiple. Tendrá que responder con Sí o No o indicar en qué medida está de acuerdo con la afirmación del 1 al 5",
	"type":	1,
    "questions": [
      {
        "id": 1,
        "description": "Me familiarizo fácilmente con gente nueva",
        "image": [
			"p1.png"
			],
        "skill": 1,
        "answers": [
          {
			"id": 1,
            "text": "1 - Totalmente en desacuerdo",
            "image": "principalHD.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "2 – En desacuerdo",
            "image": "principalHD.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "3 – Ni de acuerdo ni en desacuerdo",
            "image": "principalHD.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "4 – De acuerdo",
            "image": "principalHD.png",
            "value": 4
          },
          {
			"id": 5,
            "text": "5 – Totalmente de acuerdo",
            "image": "principalHD.png",
            "value": 5
          }
        ]
      },
      {
        "id": 2,
        "description": "¿Usted y sus compañeros se apoyan mutuamente en el trabajo?",
        "image": [
			"p2.png"
			],
        "skill": 1,
        "answers": [
          {
			"id": 1,
            "text": "Si",
            "image": "principalHD.png",
            "value": 1
          },
          {
			"id": 3,
            "text": "No",
            "image": "principalHD.png",
            "value": 0
          }
        ]
      },
      {
        "id": 3,
        "description": "Dondequiera que he estado, he sido una fuerza poderosa para el cambio constructivo.",
        "image": [
			"p3.png"
			],
        "skill": 1,
        "answers": [
          {
			"id": 1,
            "text": "1 - Totalmente en desacuerdo",
            "image": "principalHD.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "2 – En desacuerdo",
            "image": "principalHD.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "3 – Ni de acuerdo ni en desacuerdo",
            "image": "principalHD.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "4 – De acuerdo",
            "image": "principalHD.png",
            "value": 4
          },
          {
			"id": 5,
            "text": "5 – Totalmente de acuerdo",
            "image": "principalHD.png",
            "value": 5
          }
        ]
      },
      {
        "id": 4,
        "description": "Normalmente busco múltiples formas de hacer las mismas cosas en mi rutina diaria.",
        "image": [
			"p4.png"
			],
        "skill": 1,
        "answers": [
		{
			"id": 1,
            "text": "1 - Totalmente en desacuerdo",
            "image": "principalHD.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "2 – En desacuerdo",
            "image": "principalHD.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "3 – Ni de acuerdo ni en desacuerdo",
            "image": "principalHD.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "4 – De acuerdo",
            "image": "principalHD.png",
            "value": 4
          },
          {
			"id": 5,
            "text": "5 – Totalmente de acuerdo",
            "image": "principalHD.png",
            "value": 5
          }
        ]
      },
      {
        "id": 5,
        "description": "Me gusta leer cosas que estimulan mi capacidad de pensamiento.",
        "image": [
			"p5.png"
			],
        "skill": 1,
        "answers": [
		{
			"id": 1,
            "text": "1 - Totalmente en desacuerdo",
            "image": "principalHD.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "2 – En desacuerdo",
            "image": "principalHD.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "3 – Ni de acuerdo ni en desacuerdo",
            "image": "principalHD.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "4 – De acuerdo",
            "image": "principalHD.png",
            "value": 4
          },
          {
			"id": 5,
            "text": "5 – Totalmente de acuerdo",
            "image": "principalHD.png",
            "value": 5
          }
        ]
      }
    ]
}
