=== Daniel-Fernandez-UBU/riskRealUBU/javaProyect/riskrealApp/target/classes/quiz_schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "id",
      "title",
      "image",
      "language",
      "description",
      "type",
      "questions"
    ],
    "properties": {
      "id": {
        "type": "number"
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "image": {
        "type": "array",
        "items": {
          "required": [],
          "properties": {}
        }
      },
      "language": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string",
        "minLength": 1
      },
      "type": {
        "type": "number"
      },
      "questions": {
        "type": "array",
        "uniqueItems": true,
        "minItems": 1,
        "items": {
          "required": [
            "id",
            "description",
            "skill"
          ],
          "properties": {
            "id": {
              "type": "number"
            },
            "description": {
              "type": "string",
              "minLength": 1
            },
            "image": {
              "type": "array",
              "items": {
                "required": [],
                "properties": {}
              }
            },
            "skill": {
              "type": "number"
            },
            "answers": {
              "type": "array",
              "uniqueItems": true,
              "minItems": 1,
              "items": {
                "required": [
                  "id",
                  "text",
                  "value"
                ],
                "properties": {
                  "id": {
                    "type": "number"
                  },
                  "text": {
                    "type": "string",
                    "minLength": 1
                  },
                  "image": {
                    "type": "string",
                    "minLength": 1
                  },
                  "value": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== Daniel-Fernandez-UBU/riskRealUBU/riskreal/appFiles/jsonFiles/lang/quiz_1_es.json
{"id":1,"title":"Habilidades Blandas","image":["principalHD.png"],"language":"es","description":"Descripción del cuestionario","type":1,"questions":[{"id":1,"description":"Me familiarizo fácilmente con gente nueva","image":["principalHD.png"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.png","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.png","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.png","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.png","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.png","value":5,"id":5}],"skill":1},{"id":2,"description":"¿Usted y sus compañeros se apoyan mutuamente en el trabajo?","image":["principalHD.png"],"answers":[{"text":"Si","image":"principalHD.png","value":1,"id":1},{"text":"No","image":"principalHD.png","value":0,"id":3}],"skill":1},{"id":3,"description":"Dondequiera que he estado, he sido una fuerza poderosa para el cambio constructivo.","image":["principalHD.png"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.png","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.png","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.png","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.png","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.png","value":5,"id":5}],"skill":1},{"id":4,"description":"Normalmente busco múltiples formas de hacer las mismas cosas en mi rutina diaria.","image":["principalHD.png"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.png","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.png","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.png","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.png","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.png","value":5,"id":5}],"skill":1},{"id":5,"description":"Me gusta leer cosas que estimulan mi capacidad de pensamiento.","image":["principalHD.png"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.png","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.png","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.png","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.png","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.png","value":5,"id":5}],"skill":1}]}

=== Daniel-Fernandez-UBU/riskRealUBU/javaProyect/jsonFiles/lang/es_quiz_1 - copia.json
{"id":1,"title":"Habilidades Blandas","image":["principalHD.png"],"language":"es","description":"Descripción del cuestionario","type":1,"questions":[{"id":1,"description":"Me familiarizo fácilmente con gente nueva","image":["paris.jpg"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.jpg","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.jpg","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.jpg","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.jpg","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.jpg","value":5,"id":5}],"skill":1},{"id":2,"description":"¿Usted y sus compañeros se apoyan mutuamente en el trabajo?","image":["paris.jpg"],"answers":[{"text":"Si","image":"principalHD.jpg","value":1,"id":1},{"text":"No","image":"principalHD.jpg","value":0,"id":3}],"skill":1},{"id":3,"description":"Dondequiera que he estado, he sido una fuerza poderosa para el cambio constructivo.","image":["paris.jpg"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.jpg","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.jpg","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.jpg","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.jpg","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.jpg","value":5,"id":5}],"skill":1},{"id":4,"description":"Normalmente busco múltiples formas de hacer las mismas cosas en mi rutina diaria.","image":["paris.jpg"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.jpg","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.jpg","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.jpg","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.jpg","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.jpg","value":5,"id":5}],"skill":1},{"id":5,"description":"Me gusta leer cosas que estimulan mi capacidad de pensamiento.","image":["paris.jpg"],"answers":[{"text":"1 - Totalmente en desacuerdo","image":"principalHD.jpg","value":1,"id":1},{"text":"2 – En desacuerdo","image":"principalHD.jpg","value":2,"id":2},{"text":"3 – Ni de acuerdo ni en desacuerdo","image":"principalHD.jpg","value":3,"id":3},{"text":"4 – De acuerdo","image":"principalHD.jpg","value":4,"id":4},{"text":"5 – Totalmente de acuerdo","image":"principalHD.jpg","value":5,"id":5}],"skill":1}]}

=== Daniel-Fernandez-UBU/riskRealUBU/riskreal/appFiles/jsonFiles/lang/test_quiz_multi_es.json
{	
    "id": 1,
    "title": "Escenario - Habilidades Blandas",
	"image": [
		"principalHD.png"
		],
    "language": "es",
	"description": "El escenario presentado incluye una situación posible. Se tiene que seleccionad la que mejor encaje con su personalidad",
	"type":	1,
    "questions": [
      {
        "id": 1,
        "description": "El/la trabajador/a está yendo a trabajar, pero llega tarde porque se ha quedado dormido. En consecuencia, no llegará a tiempo al trabajo.",
        "image": [
			"p11.png",
			"p12.png",
			"p13.png"
			],
        "skill": 1,
        "answers": [
          {
			"id": 1,
            "text": "Aumenta la velocidad para que el viaje dure menos tiempo.",
            "image": "p111.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "Llega tarde al trabajo y pone como excusa un problema con el coche.",
            "image": "p112.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "Llama a su superior para notificarle la probabilidad de que llegue tarde.",
            "image": "p113.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "Acabar las tareas en menos tiempo del programado.",
            "image": "p114.png",
            "value": 4
          }
        ]
      }
    ]
}

=== Daniel-Fernandez-UBU/riskRealUBU/java/jsonFiles/lang/test_quiz_multi_es.json
{	
    "id": 1,
    "title": "Escenario - Habilidades Blandas",
	"image": [
		"principalHD.png"
		],
    "language": "es",
	"description": "El escenario presentado incluye una situación posible. Se tiene que seleccionad la que mejor encaje con su personalidad",
	"type":	1,
    "questions": [
      {
        "id": 1,
        "description": "El/la trabajador/a está yendo a traajar, pero llega tarde porque se ha quedado dormido. En consecuencia, no llegará a tiempo al trabajo.",
        "image": [
			"p11.png",
			"p12.png",
			"p13.png"
			],
        "skill": 1,
        "answers": [
          {
			"id": 1,
            "text": "Aumenta la velocidad para que el viaje dure menos tiempo, evitando problemas con su superior.",
            "image": "p111.png",
            "value": 1
          },
          {
			"id": 2,
            "text": "Llega tarde al trabajo y pone como excusa un problema con el coche.",
            "image": "p112.png",
            "value": 2
          },
          {
			"id": 3,
            "text": "Llama a su superior para notificarle la probabilidad de que llegue tarde.",
            "image": "p113.png",
            "value": 3
          },
          {
			"id": 4,
            "text": "Va al trabajo y trata de acabar las tareas en menos tiempo del que estaba inicialmente programado.",
            "image": "p114.png",
            "value": 4
          }
        ]
      }
    ]
}
